### ISSUE TITLE
Ubuntu 12.04

### ISSUE THREAD

**Issue by ignacio82** [jlengrand/FaceMovie#2]
Hi Julien,
I'm trying to install FaceMovie in my ubuntu 12.04. I'm following the steps from github but I get the following error:
python facemovie/Facemoviefier.py -h
Traceback (most recent call last):
  File "facemovie/Facemoviefier.py", line 16, in <module>
    from facemovie import Facemovie
ImportError: No module named facemovie

If I run 
cp Facemoviefier.py ../
and then 
python Facemoviefier.py
everything seems to work. But, when i run

python Facemoviefier.py -i /home/ignacio/Pictures/prueba/ -o /home/ignacio/Pictures
I get
Selected profile is : frontal_face
Traceback (most recent call last):
  File "Facemoviefier.py", line 164, in <module>
    my_job.run()
  File "Facemoviefier.py", line 129, in run
    self.init_facemovie()
  File "Facemoviefier.py", line 39, in init_facemovie
    self.face_params = FaceParams.FaceParams(par_fo, self.args['param'])  
  File "/media/Seagate/Downloads/facemovie/FaceMovie/facemovie/FaceParams.py", line 41, in **init**
    self.face_cascade = cv.Load(os.path.join(xml_folder, cascade_name))
TypeError: OpenCV returned NULL

Thanks for the help!

PS: ~/Downloads/facemovie/FaceMovie$ ./run.sh 
Running FaceMovie from Script !
Traceback (most recent call last):
  File "./facemovie/Facemoviefier.py", line 16, in <module>
    from facemovie import Facemovie
ImportError: No module named facemovie

**Comment by jlengrand** [comment]
The problem comes from the fact that I added the root folder to my PATH in Eclipse. 

To fix it, you can either : 
- cp Facemovifier to the application root folder (that you already did), and then run your commands using the -r option. 
  Ex: python Facemoviefier.py -r facemovie -i /home/ignacio/Pictures/prueba/ -o /home/ignacio/Pictures
- Add the root folder to your PYTHON_PATH:
  In the end of your .bashrc, add the line :
  PATH=$PATH:/path/to/facemovie/root

Then it should work.

Thanks you for the feedback, you definitely help me make the application better !

**Comment by ignacio82** [comment]
It seems to work but I can not find the output file...

~/Downloads/facemovie/FaceMovie$ python Facemoviefier.py -r facemovie -i /home/ignacio/Pictures/prueba/ -o /home/ignacio/Pictures
Selected profile is : frontal_face

# Sorting files using file name

1 faces found for 2012-06-08-190128

# 1 faces found for 2012-06-09-075403

Saving output video :
Output #0, avi, to '/home/ignacio/Pictures/output.avi':
    Stream #0.0: Video: [0][0][0][0] / 0x0000, yuv420p, 1280x960, q=2-31, 78643 kb/s, 90k tbn, 3 tbc
Saving frame 1 / 2
Saving frame 2 / 2
FaceMovie exited successfully!
ignacio@ignacio-nettop:~/Downloads/facemovie/FaceMovie$ ls /home/ignacio/Pictures
2012  prueba  scanned  wallpapers  Webcam

**Comment by jlengrand** [comment]
Can you please try with the -t i option and tell me the outcome ?

**Comment by ignacio82** [comment]
python Facemoviefier.py -r facemovie -t -i /home/ignacio/Pictures/prueba/
-o /home/ignacio/Pictures
usage: Facemoviefier.py [-h]
                        [-p
{upper_body,profile_face,lower_body,frontal_face,full_body,?}]
                        -i INPUT -o OUTPUT [-r ROOT] [-e] [-c]
                        [-d CROPDIMS CROPDIMS] [-t {v,i,s}] [-s {n,e}]
                        [--fps
{2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19}]
Facemoviefier.py: error: argument -t/--type: expected one argument

On Sat, Jun 9, 2012 at 11:12 AM, julien Lengrand-Lambert <
reply@reply.github.com

**Comment by jlengrand** [comment]
python Facemoviefier.py -r facemovie -t i /home/ignacio/Pictures/prueba/ -o /home/ignacio/Pictures

You entered -t -i :)

**Comment by ignacio82** [comment]
python Facemoviefier.py -r facemovie -t i /home/ignacio/Pictures/prueba/ -o
/home/ignacio/Pictures
usage: Facemoviefier.py [-h]
                        [-p
{upper_body,profile_face,lower_body,frontal_face,full_body,?}]
                        -i INPUT -o OUTPUT [-r ROOT] [-e] [-c]
                        [-d CROPDIMS CROPDIMS] [-t {v,i,s}] [-s {n,e}]
                        [--fps
{2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19}]
Facemoviefier.py: error: argument -i/--input is required

but if i do
 python Facemoviefier.py -r facemovie  -i /home/ignacio/Pictures/prueba/ -o
/home/ignacio/Pictures -t i
Selected profile is : frontal_face

# Sorting files using file name

1 faces found for 2012-06-08-190128

# 1 faces found for 2012-06-09-075403

Saving output images :
Saving /home/ignacio/Pictures/2012-06-08-190128.png
Saving /home/ignacio/Pictures/2012-06-09-075403.png
FaceMovie exited successfully!

-t v does not produce a video file :_(

On Sat, Jun 9, 2012 at 11:21 AM, julien Lengrand-Lambert <
reply@reply.github.com

**Comment by jlengrand** [comment]
Ok, then the problem comes from the video stub of OpenCV . 
I'll have a look at it and let you know. 

python Facemoviefier.py -r facemovie -t i /home/ignacio/Pictures/prueba/ -o
/home/ignacio/Pictures doesn't work because it expects -i in front of  /home/ignacio/Pictures/prueba

-t i => change output mode to image
-i => provide the folder where input images are stored.

**Comment by jlengrand** [comment]
Hey ignacio, 

I think I solved the video problem. I also did some work to avoid import problems. 

Could you please try the following : 
- clone the last version of the code :

`git clone git://github.com/jlengrand/FaceMovie.git -b 0.8.1-main`
- download the samples [here](http://dl.dropbox.com/u/4286043/GH/FaceMovie/packaging/ressources/samples.zip), and extract them in a samples folder.
- run the Facemovie from the root folder :

`python Facemovifier.py -i folder/to/samples -o .`

Check if you have the video, called output.avi

This works fine for me. 
Let me know ;)

**Comment by ignacio82** [comment]
Now when i run

python Facemoviefier.py -i /media/Seagate/Pictures/samples/ -o
/home/ignacio/Pictures

I get the .avi. The problem is that it seems to be corrupt.

Ubuntu's default movie player says "An error occurred Failed to create
output image buffer of 816x626pixels"

mplayer and vlc show a noise video. See
screenshothttps://www.dropbox.com/s/rt0v0m2lozm28rq/Screenshot%20from%202012-06-09%2014%3A11%3A41.pngand
video https://www.dropbox.com/s/u8jp37pgo8fb97w/output.avi

Thanks for your work!

On Sat, Jun 9, 2012 at 1:31 PM, julien Lengrand-Lambert <
reply@reply.github.com

**Comment by jlengrand** [comment]
Hum..

Weird, can you please check that you have all the packages listed here
installed ?
http://opencv.willowgarage.com/wiki/InstallGuide%20%3A%20Debian

2012/6/9 ignacio82 <
reply@reply.github.com

**Comment by ignacio82** [comment]
I didn't have a few but installing them did't solve the problem :_(

On Sat, Jun 9, 2012 at 2:21 PM, julien Lengrand-Lambert <
reply@reply.github.com

**Comment by ignacio82** [comment]
This is the workaround the problem i'm using right now.
1.
python Facemoviefier.py -i /media/Seagate/Pictures/samples/ -o
/home/ignacio/Pictures -t i
2.
mencoder mf://*.png -mf w=800:h=600:fps=3:type=png -ovc copy -oac copy -o
output.avi
And this is the output i
get.https://www.dropbox.com/s/u8jp37pgo8fb97w/output.avi

**Comment by jlengrand** [comment]
Hey, Thanks for having found a solution !

I spent some time trying to solve the problem yesterday, but It is quite difficult as the last solution already works fine for me.
Would you be willing to continue testing my code?

Thank you again for the mencoder solution, that'd be a good solution if OpenCV doesn't give good results on lots of computers. 

Have you tried with some of your images?

**Comment by jlengrand** [comment]
I searched on the internet for people having the same kind of problem than you with OpenCV gstreamer backend. 
Could you please try with the new codec I have chosen ?

To do this: 
- **Check if you already are on branch 0.8.1-main**:
  ```git status
  # On branch 0.8.1-main

```

- If so, pull the last version of the code :
```

git pull

```
and run the Facemovie again :
```

python Facemoviefier.py -i /media/Seagate/Pictures/samples/ -o
/home/ignacio/Pictures

```

- **otherwise**, directly clone the 0.8.1-main branch :
```

git clone git://github.com/jlengrand/FaceMovie.git -b 0.8.1-main

```
- and try Facemovie again. 

Is the result better?

**EDIT:** vlc seem to have problems with this codec. But it works fine with totem for me.
Let me know.
```

**Comment by ignacio82** [comment]
It works!

I'll be happy to try newer versions :-)

Thanks for your work!

-Ignacio

On Sun, Jun 10, 2012 at 5:06 AM, julien Lengrand-Lambert <
reply@reply.github.com

**Comment by jlengrand** [comment]
Glad  the solution was finally found !

Thanks for your help, and for having taken the time to report issues. You definitely help making the product better!
Did you like the outcome of the processing you tried ?
